[package]
name = "poe_api_process"
version = "0.1.6"
edition = "2021"
publish = ["crates-io"]
authors = ["Jerome Leong <jeromeleong1998@gmail.com>"]
description = "Poe API for rust"
repository = "https://github.com/jeromeleong/poe_api_process"
license = "MIT"
keywords = ["poeapi", "ai"]
categories = ["api-bindings"]

[dependencies]
reqwest = { version = "0.12.15", features = ["json", "stream"] }
tokio = { version = "1.44.2", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
futures-util = "0.3.31"
async-trait = "0.1.88"
thiserror = "2.0.12"
bytes = "1.10.1"
tracing = "0.1.41"

[dev-dependencies]
test-log = { version = "0.2.17", features = ["trace"] }
dotenv = "0.15.0"
env_logger = "0.11.8"